name: "githubapp"
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
 
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: github app
      
      run: |
       echo application_id:${{secrets.APPLICATION_ID}}
       echo application_privatekey:${{secrets.APPLICATION_PRIVATE_KEY}}
       echo GITHUB_TOKEN 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
       curl https://api.github.com/users/SiyaaJhawar
       curl -i -H "Authorization: bearer $GTHUB_TOKEN" -d '{"title" : "Hello world"}' https://api.github.com/users/SiyaaJhawar/repos/SiyaaJhawar/learning-/issues

       
      
     
       
    

      
