name: Call a reusable workflow

on:
  pull_request:
    branches:
      - none

 

jobs:
  call-workflow:
    uses: SiyaaJhawar/learning-/.github/workflows/main.yml@main
    with:
     
     config-path: .github/main.yml
          
    secrets: inherit
      
   
       
 
