name: Generate Private Key

 
  
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_private_key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate private key
      run: |
        openssl genpkey -algorithm RSA -out private_key.pem -aes256
      

    - name: Store private key as a GitHub Actions secret
    
      with:
        name: private_key
        key-file: private_key.pem
