on:
  workflow_dispatch:
    inputs:
      Day:
      Month:
    
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
     Day: Monday
     Month: December
    outputs:
      output1: ${{ steps.step1.outputs.Day}}
      output2: ${{ steps.step2.outputs.Month}}
    steps:
      - id: step1
        run: echo "${{env.Day}}">> $GITHUB_OUTPUT
      - id: step2
        run: echo "${{env.Month}}" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ env.Day == 'Monday' && env.Month == 'December'}}
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  job3:
    runs-on: ubuntu-latest
    needs:  job2
    if: | 
        always() && needs.job2.result == 'skipped'
    steps:
      - run: echo 'the job2 is skipped'

     
     
    
