on:
  workflow_dispatch:
    inputs:
      Day:
      Month:
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.Day}}
      output2: ${{ steps.step2.outputs.Month }}

      
    steps:
      - id: step1
        run: |
         my_var1=Day
          echo "my_var1=Monday" >> $GITHUB_OUTPUT
      - id: step2
        
        run: |
         my_var2=Month
          echo "my_var2=December" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ my_var1 == 'Monday' && my_var2 == 'December' }}
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  job3:
    runs-on: ubuntu-latest
    needs:  job2
    if: | 
        always() && needs.job2.result == 'skipped'
    steps:
      - run: echo 'the job2 is skipped'

     
     
    
