on:
  workflow_dispatch:
    inputs:
      Day: 
      Month:
        required: true
        type: string
env:
     DAY: 'Monday'
     MONTH: 'December'
jobs:
  job1:
    runs-on: ubuntu-latest
   
    outputs:
      output1: ${{ steps.step1.outputs.DAY}}
      output2: ${{ steps.step2.outputs.MONTH}}
    steps:
      - id: step1
        run: echo '${{env.DAY}}'>> $GITHUB_OUTPUT
      - id: step2
        run: echo '${{env.MONTH}}'>> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ inputs.Day == 'Monday' && inputs.Month == 'December'}}
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  job3:
    runs-on: ubuntu-latest
    needs:  job2
    if: | 
        always() && needs.job2.result == 'skipped'
    steps:
      - run: echo 'the job2 is skipped'

     
     
    
