on:
  workflow_dispatch

env:
  DAY: Monday
  MONTH: December
  

   
  

jobs:
  job1:
    runs-on: ubuntu-latest
   
    outputs:
      output1: ${{ steps.step1.outputs.env.DAY}}
      output2: ${{ steps.step2.outputs.env.MONTH }}
    steps:
      - id: step1
        run: echo "$DAY" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "$MONTH" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: ${{ DAY == 'Monday' && MONTH == 'December' }}
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  job3:
    runs-on: ubuntu-latest
    needs:  job2
    if: | 
        always() && needs.job2.result == 'skipped'
    steps:
      - run: echo 'the job2 is skipped'

     
     
    
