name: "Hit a webhook"
 
on:
  push:
    
  workflow_dispatch:
 
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        
        curl -Ss "https://www.boredapi.com/api/activity" |\
         jq -r '.[]'|\
         while read api
         do
            curl -Ss "https://www.boredapi.com/api/activity"
         done | jq 'if type == "array" then .[] | .id elif type == "object" then .id else empty end'
         
       # curl "https://www.boredapi.com/api/activity"
       # var keys=JSON.parse(response.body).keys();
       # var value=keys[0];
        
         
      
         # if let dictionary   = json.object {
  
         #   for (key, value) in dictionary {

           #   println("key: \(key), value: \(value)")

         #  }

          #  }
         
        
        
       
        
        
               
            
              
           
        
         
         
        
        
        
        
        
        
         
        
 

   
       
         
       
