name: "Hit a webhook"
 
on:
  push:
    
  workflow_dispatch:
 
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl --request GET \
        --url "https://www.boredapi.com/api/activity" | jq
        var resData = json.decode(response.body);
Map myMap = resData;

myMap.forEach((key, value) {
  print('$key : $value');
}); 
         
         
        
        
       
        
        
               
            
              
           
        
         
         
        
        
        
        
        
        
         
        
 

   
       
         
       
