name: "Hit a webhook"
 
on:
  push:
    
  workflow_dispatch:
 
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        # curl -Ss "https://www.boredapi.com/api/activity"
        #curl "https://www.boredapi.com/api/activity"
        echo "::set-output name=releasetag::$(curl -s "https://www.boredapi.com/api/activity")
         #var keys=JSON.parse(response.body).keys();
         #var value=keys[0];
       
     
         # for activity in $( echo "$json" | jq '.activity{}') ; do 
          #  echo curl ... ${"https://www.boredapi.com/api/activity"}...
         # done 
        
      #  curl -Ss "https://www.boredapi.com/api/activity"
        # jq -r '.[] | @https://www.boredapi.com/api/activity' |\
        # while read api
       #  do
         #   curl -Ss "https://www.boredapi.com/api/activity"
         #done | jq 'if type == "array" then .[] | .id elif type == "object" then .id else empty end'
         
         
        
         
      
         # if let dictionary   = json.object {
  
         #   for (key, value) in dictionary {

           #   println("key: \(key), value: \(value)")

         #  }

          #  }
         
        
        
       
        
        
               
            
              
           
        
         
         
        
        
        
        
        
        
         
        
 

   
       
         
       
